name: Build and Deploy to npm

on:
  push:
    branches:
      - main # Deploy only from the main branch

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lets/*' # Specify the Node.js version
          cache: 'npm'

      # Step 3: Configure npm for scoped packages
      - name: Configure npm for scoped package
        run: |
          echo "@team-good-io:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Run tests (optional but recommended)
      # - name: Run tests
      #   run: npm test

      # Step 6: Build the package
      - name: Build the package
        run: npm run build
        
      - run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
